version: 2
jobs:
  build:
    machine: true
    environment:
        GRADLE_OPTS: -Dorg.gradle.daemon=false
    steps:
      - checkout
      - run: ./gradlew check assemble
      - run: make test
      - run: docker build -t tower-backend:latest tower-backend/
      - run: docker build -t tower-web:latest tower-web/

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
